# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eca4ac779d30daef28b6dcf9b02ba12adeef693b6f8cd70082fcb0a22016dfe511e85b3122b224606262ebd0d98f7113dd4252ede9572a3fd3f596aeedcbcc68

test:
  secret_key_base: 00646d904ff4bc632cb7e0464d5c8520dcdaad3ece0ff29df10436104cc2b831bd3c9b1ab3522f82215dbb1b494940f000c323e5daf3b19cef5ecedef615487f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
